---
- hosts: localhost
  tasks:
  - name: testing custom module
    incapsulav1:
     key1: fail me
     key2: value2
    register: output

  - name: debugging output
    debug:
      msg: "{{ output }}"
